theme: jekyll-theme-modernist
title: Probabilidad y variables aleatorias para ML con R y Python
description: https://www.udemy.com/course/probabilidad-y-variables-aleatorias-para-ml-con-r-y-python/?couponCode=B85F8D52148DF5AAD8F7