name: "Probabilidad y variables aleatorias para ML con R y Python"
output_dir: "../docs"
navbar:
  title: "Probabilidad y variables aleatorias para ML con R y Python"
  left:
  - text: "Home"
   href: index.html
  - text: "Tema 0"
   href: Tema-0---Prerequisitos.html
output:
  html_document:
 theme: cosmo
